batch_size: 512
augmentation: true
transform_type: LFBE_Delta
sample_rate: 16000
n_mfcc: 13
n_mels: 13
n_fft: 480
hop_length: 160
f_min: 20
f_max: 4000
augmentation: true
noise_dir: YOUR_PATH
noise_prob: 0.8
snr:
- -5
- 10
shift:
- -0.1
- 0.1
spec_augment: true
n_time_masks: 2
time_mask_param: 20
n_freq_masks: 2
freq_mask_param: 20
root: YOUR_PATH
download: true
version: 2
wanted_words:
- down
- go
- left
- no
- off
- on
- right
- stop
- up
- yes
lr: linear_decay
lr_init: 1e-3
lr_end: 1e-4
model: EdgeCRNN
in_channels: 1
hidden_size: 64
width_multiplier: 1
num_classes: 12
seed: 42
ckpt_dir: YOUR_PATH
device: cuda:0
max_epochs: 500
gradient_clip_val: 5
