batch_size: 100
augmentation: true
transform_type: logmel
sample_rate: 16000
n_fft: 512
win_length: 480
hop_length: 160
n_mels: 40
augmentation: true
noise_dir: YOUR_PATH
noise_prob: 0.8
snr:
- -5
- 10
shift:
- -0.1
- 0.1
spec_augment: true
n_time_masks: 2
time_mask_param: 20
n_freq_masks: 2
freq_mask_param: 5
root: YOUR_PATH
download: true
version: 2
wanted_words:
- down
- go
- left
- no
- off
- on
- right
- stop
- up
- yes
lr: cosine
base_lr: 1e-1
warmup_epochs: 5
model: BCResNet
in_channels: 1
num_classes: 12
mul_factor: 3
seed: 42
ckpt_dir: YOUR_PATH
device: cuda:0
max_epochs: 200
gradient_clip_val: null
