batch_size: 128
augmentation: true
transform_type: MFCC
sample_rate: 16000
n_mfcc: 80
f_min: 0
f_max: 2048
n_mels: 80
win_length: 400
hop_length: 160
n_fft: 512
augmentation: true
noise_dir: YOUR_PATH
noise_prob: 0.8
snr:
- -5
- 10
shift:
- -0.1
- 0.1
spec_augment: true
n_time_masks: 2
time_mask_param: 20
n_freq_masks: 2
freq_mask_param: 20
root: YOUR_PATH
download: true
version: 2
wanted_words:
- down
- go
- left
- no
- off
- on
- right
- stop
- up
- yes
lr: 0.001
model: MDTC
in_channels: 80
out_channels: 64
kernel_size: 5
stack_num: 4
stack_size: 4
hidden_size: 64
num_classes: 12
seed: 42
ckpt_dir: YOUR_PATH
device: cuda:0
max_epochs: 100
gradient_clip_val: null
